name: "Read the Docs Pull Request Preview"
author: "@readthedocs"
description: "Update PR description with a link to the rendered version of the documentation on Read the Docs"

branding:
  color: gray
  icon: robot

inputs:
  project-slug:
    description: "Project's slug on Read the Docs"
    required: true
  project-language:
    description: "Project's language on Read the Docs"
    default: "en"
    required: false
  message-template:
    description: "Template message to use for the PR body"
    default: |
      ----
      📚 Documentation preview 📚: {docs-pr-index-url}
    required: false
  platform:
    description: "Read the Docs Community or Read the Docs for Business (community or business)"
    default: "community"
    required: false
  single-version:
    description: "Site is a single version project, so link to the top level."
    default: 'false'
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "node16"
  main: 'dist/index.js'
