name: readthedocs/actions
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run action preview
        uses: ./preview
        with:
          project-slug: "readthedocs-preview"
